name: Build Docs
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'bin'
      - 'include'
      - 'lib'
      - 'pyenv.cfg'
      - 'requirements.txt'
      - '.gitignore'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        # If you're using actions/checkout@v2 you must
        # set persist-credentials to false in most cases
        # for the deployment to work correctly.
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Docs
        run: |
          pdoc3 --html --output-dir docs mean_variance_hedge
      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.